### PR TITLE
Use host= keyword rather than ip=

### PR DESCRIPTION
**Pull request by mrocklin**
This will change in the next release.  We should merge this and release after we next release dask/distributed.

### CODE REVIEW

**Comment by lesteve** [comment]
@mrocklin do you think we should merge this one? My understanding:
* `ip` is marked deprecated in `LocalCluster` docstring but using `ip` does not create a warning in master yet.
* there was a failure at the time you opened the PR (distributed 1.28.1) which seemed genuine (the test is supposed to check that by default the scheduler starts on an IP address that is reachable from other nodes). This seems fixed in distributed 2.1 although I was not able to  find the related entry in the distributed changelog.

More details: this PR was failing when @mrocklin originally opened the PR (June 13), see this [Travis log](https://travis-ci.org/dask/dask-jobqueue/jobs/549040567). The error was:

```
_______________________________ test_forward_ip ________________________________
    def test_forward_ip():
        ip = "127.0.0.1"
        with PBSCluster(
            walltime="00:02:00",
            processes=4,
            cores=8,
            memory="28GB",
            name="dask-worker",
            host=ip,
        ) as cluster:
            assert cluster.local_cluster.scheduler.ip == ip
    
        default_ip = socket.gethostbyname("")
        with PBSCluster(
            walltime="00:02:00", processes=4, cores=8, memory="28GB", name="dask-worker"
        ) as cluster:
>           assert cluster.local_cluster.scheduler.ip == default_ip
E           AssertionError: assert '127.0.0.1' == '0.0.0.0'
E             - 127.0.0.1
E             + 0.0.0.0
dask_jobqueue/tests/test_jobqueue_core.py:104: AssertionError
=============== 1 failed, 78 passed, 15 skipped in 2.92 seconds ================
```

I was able to reproduce the original error locally with distributed=1.28.1.

**Comment by mrocklin** [comment]
> ip is marked deprecated in LocalCluster docstring but using ip does not create a warning in distributed master yet.

Right.  At one point in development we were adding a warning if the user used `ip=`, but then after submitting this PR I decided that that was probably too aggressive, particularly because this would effectively force dask-jobqueue to drop Python 2 going forward (dask 2.0 drops the `ip=` keyword and Python 2, so dask-jobqueue would have to either accept annoying warnings, or drop Python 2 as well).  I thought that HPC users are probably a little bit less able to move to Python 3 and so there wasn't a rush.

I would be happy to merge this any time if you like.  I'll leave it to you.

**Comment by lesteve** [comment]
We dropped Python 2 support for 0.6 (roughly 2 weeks ago). 0.6 was supposed to be compatible with dask >= 2 but it looks like we missed a few things, which I am trying to fix in the next release.

About dropping Python 2 support for HPC users, all of the people around me use Python 3 already with a conda installed as a user in a shared network drive. If you want to bring in other people that may have another experience from HPC setup into the conversation, you would be more than welcome to do so!

**Comment by mrocklin** [comment]
If the dask-jobqueue maintainers want to drop Python 2 then I'm all for
it.  I just didn't want to force the issue.

**Comment by lesteve** [comment]
Fine, let's merge this one then!

**Comment by lesteve** [comment]
Thanks @mrocklin!

**Comment by lesteve** [comment]
> 0.6 was supposed to be compatible with dask >= 2 but it looks like we missed a few things, which I am trying to fix in the next release.

BTW @guillaumeeb or @mrocklin if you could give me the rights on PyPI, that would be great! My user name on PyPI is lesteve as well.

**Comment by mrocklin** [comment]
Done!

**Comment by lesteve** [comment]
Great thamks a lot!

**Pull request merged**
