### PR TITLE
Add a cluster detailed status method

### LINKED ISSUE #11: Implement a cluster status method, to now if worker are really running
Currently, we only know that we have submitted some jobs to a cluster scheduler. We don't know if these jobs are running or queued, or in any other state.

What do you think of implementing a kind of status method?

In the PBS case for example, it would issue a qstat call, and get the PBS scheduler status of every jobs handled by the Dask cluster.

Not sure if this is really needed, as we are able with the use of Dask Client to know the real size of the cluster (and maybe by some other means). 

Maybe this issue is just about documenting how to retrieve the information about a cluster state, either by job scheduler (eg. PBS) API, either using Dask API.

### PR DESCRIPTION
**Pull request by guillaumeeb**
Closes #11.

Main concern here: is this really useful in addition to cluster.__repr__ or client.__repr__.
Personnaly, I like to have kind of detailed status, but find it only useful in some specific cases.

Any other feedback quite welcome.

### CODE REVIEW

**Comment by guillaumeeb** [comment]
Here is how it looks:

image

**Comment by mrocklin** [comment]
I like the idea here.  Some thoughts:

1.  Is this something that we want to coordinate with other cluster managers (dask-yarn, dask-kubernetes).  If so, how?  cc @jcrist @jacobtomlinson 
2.  If yes, then what kind of data would we standardize around that is common to all three.  Should we also provide this data in a structured way?
2.  Would this be better as a dashboard plot or ipywidget that updated in real time?

**Comment by jhamman** [comment]
> Is this something that we want to coordinate with other cluster managers (dask-yarn, dask-kubernetes). If so, how? cc @jcrist @jacobtomlinson

I'd argue that the running/pending/finished job/worker classification is going to be widely applicable (even for a LocalCluster). That said, I don't know enough about the other systems to generalize these classifications.

Also, +1 on adding something like this to the dashboard.

**Comment by jacobtomlinson** [comment]
These would definitely be useful in `dask-kubernetes`. Running and Pending would be easy to implement, completed workers get cleaned up automatically so that doesn't really work for that.

**Comment by jhamman** [comment]
Is this worth reviving? I still think this would be a worthwhile addition.

**Comment by guillaumeeb** [comment]
I guess I didn't know what to do with @mrocklin comments... I feel this is applicable to other cluster managers, but I don't know how to standardize it, so that it can be easily migrated upstream and then in other projects. How to represent job vs pod in dask-kubernetes vs only processes in LocalCluster...

And probably was waiting for some more discussion on the form it should take.

**Comment by mrocklin** [comment]
I'm happy to not standardize things for a while.  Please don't consider my comments as blockers on any progress here.

**Comment by guillaumeeb** [comment]
So what do we want here to do here:

- I'm not sure the simple html representation is really useful, is it?
- Do anyone has a proposal on the format? Dashboard (I don't know how to do dashboard addition, and this may have to go upstream?), Widget, simple HTML, some table like Dataframes?
- What can we use to make the job/pod/other notion generic? Use some key if it exist, like our worker_key that adaptive uses? Anything else?

I guess I need more precise feedback :slightly_smiling_face:.

**Comment by mrocklin** [comment]
My first thought was to suggest that the cluster object have a `cluster.status()` method or something similar return a standarized data structure that could be placed into a table.  A dashboard page could then be built that called that function periodically.

However, then I thought about how we might separate the cluster manager from the scheduler, at which point we'll no longer have access to the dashboard (except by explicitly passing messages).  It might be that this information might also be expressible through something like a JupyterLab extension, similar to what @ian-r-rose is building at https://github.com/dask/dask-labextension/pull/31

**Comment by jacobtomlinson** [comment]
It's been a long time since this PR had any activity so I'm going to close it out.

**Pull request closed without merging**
