### PR TITLE
Alternative way of listening on all interfaces for the bokeh server

### LINKED ISSUE #126: Adaptive prematurely killing workers
I think this may be related to #122 but not sure so I'll post it as it's own issue.

When I start up a PBS cluster with adaptive, it starts up the minimum number of workers, but then kills all of them after about 10 seconds. This is not the case if I scale without using adaptive. I'm attaching a notebook to show a simple example and other information. 

[Adaptive Example](https://gist.github.com/josephhardinee/23594e44d943a6f97fc689842d501952)

### PR DESCRIPTION
**Pull request by lesteve**
This is an alternative to #129. Not sure which one is preferable to be completely honest ... one difference that may matter is that the scheduler does not listen on all interfaces. 

This is more in the spirit of https://github.com/dask/dask-jobqueue/issues/90#issue-340311408. I discovered through looking at the source code, that you can pass a `(address, port)` address fine to the `diagnostics_port` despite its name. Thanks to this, the bokeh diagnostics server will listen on all interfaces.

Close #126.

### CODE REVIEW

**Comment by guillaumeeb** [comment]
And by the way, should we update distributed keyword name? This could break other things I imagine.

**Comment by lesteve** [comment]
> I think I prefer this way, except I would still bind scheduler itself on all interfaces by default if no interface is provided. This should prove compatible with more network setup as default, even if only on edge cases.

Can you give a quick example of a cluster setup when it is useful to have the scheduler listen on all interfaces?

**Comment by guillaumeeb** [comment]
No I cannot :), I just suspect it could happen. But in such a case workaround would be to pass ip kwargs when initializing cluster object. So nevermind.

**Comment by guillaumeeb** [comment]
@lesteve feel free to revert your last commit, as discussed in previous comment, I don't have a strong argument for listening on all interfaces for scheduler, and if it is needed it can easily be done with kwargs.

**Comment by guillaumeeb** [comment]
I will merge this once travis is OK.

**Pull request merged**
