### PR TITLE
add ncpus_per_host option to LSFCluster

### PR DESCRIPTION
**Pull request by louisabraham**
fix https://github.com/dask/dask-jobqueue/issues/172

### CODE REVIEW

**Comment by louisabraham** [comment]
@willirath the reformatting is done in separate commits, I don't understand what you mean.

**Comment by willirath** [comment]
Sorry, I was not as verbose as I should have been: All these commits will be squashed to one commit representing this PR. Then, we'll have `git blame` telling the user that the reformatted lines have been changed in order to fix the LSFCluster issue.

**Comment by louisabraham** [comment]
I'm am no expert in github, but I think it only happens if you actually squash.

Since I forked directly from the current HEAD, you can actually do [Rebase and merge](https://help.github.com/articles/about-pull-request-merges/#rebase-and-merge-your-pull-request-commits).

If you prefer, I can cherry-pick the commits and turn off my editor's autoformatting.

**Comment by guillaumeeb** [comment]
Hm, I think @willirath has got a point. It will be clearer to avoid reformatting for this issue.
The rule here is to only use squash and commit, so we will lose the detail commit history. If you could only implement the changes necessary to fix the identified issue this would be better.

**Comment by louisabraham** [comment]
Ok, I'll redo it. Anyway I think I'll need to change my code depending on your answer on #172.

Just for my personal knowledge: what is the point of using only "squash and commit"?

**Comment by willirath** [comment]
> Just for my personal knowledge: what is the point of using only "squash and commit"?

The master branch evolving in steps that make sense from a functional point of view rather than reflecting the (often random) steps it took to develop and implement the solution.

Taking this PR as an example, we'd have one commit telling the reader "LSFCluster now correctly starts all threads on the same node and here's all we did to achieve that." vs different commits that make it very hard to later understand what happened.

**Comment by guillaumeeb** [comment]
Thanks anyway @louisabraham for all the work you've already done, and for sticking with this! 
Sorry I was not really available today to answer your questions.

**Comment by louisabraham** [comment]
I am the one who thanks both of you for actually taking more time to explain things to me than it would take you to fix the bug :)

**Comment by willirath** [comment]
> I am the one who thanks both of you for actually taking more time to explain things to me than it would take you to fix the bug :)

I'm glad you take it this way! Communicating criticism in a well-meaning and constructive manner is not trivial and it'd probably be easy to read my remarks in an offensive tone.

**Pull request closed without merging**
