### PR TITLE
add temporary security if set to True

### LINKED ISSUE #525: Create temporary security context by default if security is set to True
Inspired by dask/dask-cloudprovider#222, it very convenient if tls certificates can be generated using dask's built-in ``Security.temporary()`` if  ``Security=True``

Currently blocked by #520

### PR DESCRIPTION
**Pull request by riedel**
add cryptography dependency to htcondor testing
fix extra_dependency for testing: tests_require seems to be deprecated

Fixes #525

### CODE REVIEW

**Comment by riedel** [comment]
rebased on #524 to actually check if the prerequisites are given

**Comment by riedel** [comment]
needs to be rebased once #524 is merged.

**Comment by riedel** [comment]
@guillaumeeb: many thanks for merging #524!! This is the last remaining bit of the bunch of PRs. This, however, is not much of a priority. It just aligns things a bit with other cluster implementations for convenience..

**Review by guillaumeeb — APPROVED** [review]
Thanks @riedel!

**Pull request merged**
