### PR TITLE
use dask.utils.tmpfile as distributed.utils.tmpfile was deprecated 

### LINKED ISSUE #528: distributed.utils.tmpfile used in core.py to create the jobscript is deprecated
See:
https://github.com/dask/distributed/blob/11c41b525267cc144caa8d077b84a0939fecae97/distributed/utils.py#L1417-L1427

Imported here:
https://github.com/dask/dask-jobqueue/blob/9944654374a4e06d3a3289069d2ec0a61ae96162/dask_jobqueue/core.py#L20

Used here:
https://github.com/dask/dask-jobqueue/blob/9944654374a4e06d3a3289069d2ec0a61ae96162/dask_jobqueue/core.py#L303

### PR DESCRIPTION
**Pull request by riedel**
Fixes #528

### CODE REVIEW

**Review by andersy005 — APPROVED** [review]
Looks good to me 👍🏽

**Comment by andersy005** [comment]
Do we need to update the version requirement for dask or does this work with our existing version requirement?

**Comment by riedel** [comment]
> Do we need to update the version requirement for dask or does this work with our existing version requirement?

Should be OK:
https://github.com/dask/dask/blob/c48623bcd6e5fd7699b15c0e611ee38fff167ff6/dask/utils.py#L103-L118

https://github.com/dask/dask-jobqueue/blob/9944654374a4e06d3a3289069d2ec0a61ae96162/requirements.txt#L1

**Comment by riedel** [comment]
@andersy005 :  you might have made a point, but it was not me: #530

**Review by guillaumeeb — APPROVED** [review]
Thanks @riedel for all your involvement!

**Pull request merged**
