### PR TITLE
Initial Travis configuration (rebased and fixed)

### PR DESCRIPTION
**Pull request by lesteve**
I fixed the conflicts in #13 and got Travis working on my fork, see [this Travis build](https://travis-ci.org/lesteve/dask-jobqueue/builds/358888076).

Closes #13.

I would have opened a PR on @jhamman fork but because of the conflicts this is not very convenient so I opened a new PR instead.

### CODE REVIEW

**Comment by lesteve** [comment]
Full disclosure: I am certainly not a docker expert, so I did the minimal change to get Travis to work without guarantee that this follows best docker practices.

**Comment by mrocklin** [comment]
I'm very glad to see you working on this @lesteve :)  I'm curious have you been using dask-jobqueue on your own?

Also, to reduce build times we might want to add the `nomkl` package to the environment.

**Comment by jhamman** [comment]
@lesteve - this makes me very happy to see. Thanks for stepping up. No strong objections from me on the changes you made.

**Comment by mrocklin** [comment]
It works!  That's quite exciting :)

Now we just need to make an SGE system, which should be comparatively easy :)

**Comment by mrocklin** [comment]
@jhamman now that we have a system in place do you think some of the system administrators at NCAR would have time an interest in submitting a solution for PBS?

**Comment by lesteve** [comment]
> I'm very glad to see you working on this @lesteve :) I'm curious have you been using dask-jobqueue on your own?

Happy this is useful! I have been watching dask-drmaa and dask-jobqueue lately with the near-future goal to make using our local SGE cluster more user-friendly for researchers. I have used only dask-drmaa so far and only for toy problems.

**Comment by lesteve** [comment]
It would be great, I definitely plan to try test dask on our SGE cluster more extensively by then!

**Comment by mrocklin** [comment]
I am also curious to see if adaptive scaling is effective for you.  You
might want to try the adapt method of the cluster classes.

**Comment by guillaumeeb** [comment]
@mrocklin @jhamman, I was thinking about working on a comparable solution for PBS. But if someone else is willing to work on this that's fine with me.

Maybe we should open a specific issue for PBS, and same with Slurm?

**Comment by mrocklin** [comment]
The comment about NCAR is probably optimistic.  I would not assume that the
system administrators there will have time to help with this.

**Comment by mrocklin** [comment]
@jhamman ok to merge?

**Pull request merged**
