### PR TITLE
Initial Travis CI Configuration

### LINKED ISSUE #8: Unified test suite
After we figure out CI testing in #2 we might consider refactoring the test suite into a unified `TestCase` class for common functionality.

### PR DESCRIPTION
**Pull request by jhamman**
closes #8

This only sets up the SGE sceduler. I've mostly just copied the configuration from dask-drmaa.

### CODE REVIEW

**Comment by jhamman** [comment]
@quasiben - I think you were the main developer of the the SGE CI setup for dask-drmaa. Any chance you could look over this PR and provide a few comments. The current build is failing so perhaps there is a clue in there for you.

**Comment by quasiben** [comment]
@jhamman, generally it looks good.  If you want, you could clean up dockerfile things a bit to slim down the image, but perhaps that isn't a priority right now.   I'm not sure off hand why the second slave isn't coming online.  Is this working locally ?

**Comment by jhamman** [comment]
@quasiben - thanks for taking a look. 

Running locally also doesn't seem to work: 

```bash
./start-sge.sh
Starting sge_master ... done
Recreating slave_two ...
Recreating slave_two ... done
Error response from daemon: Container 0daa6a7bfdbffed3bcdf72ba487ec2a75b7ae1809d70c844a75e8335b32d5aa6 is not running
Waiting for SGE slots to become available
Error response from daemon: Container 0daa6a7bfdbffed3bcdf72ba487ec2a75b7ae1809d70c844a75e8335b32d5aa6 is not running
Waiting for SGE slots to become available
Error response from daemon: Container 0daa6a7bfdbffed3bcdf72ba487ec2a75b7ae1809d70c844a75e8335b32d5aa6 is not running
Waiting for SGE slots to become available
Error response from daemon: Container 0daa6a7bfdbffed3bcdf72ba487ec2a75b7ae1809d70c844a75e8335b32d5aa6 is not running
Waiting for SGE slots to become available
Error response from daemon: Container 0daa6a7bfdbffed3bcdf72ba487ec2a75b7ae1809d70c844a75e8335b32d5aa6 is not running
....
```

I'll keep playing around but if you have any ideas, feel free to share.

**Comment by jhamman** [comment]
superseded by #23, thanks @lesteve!

**Pull request closed without merging**
