### PR TITLE
Inherit from distributed.Cluster

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/dask/dask-jobqueue/issues/16

### CODE REVIEW

**Comment by jhamman** [comment]
This looks good to me. I'll try to test it out in the next few hours. Thanks!

**Comment by jhamman** [comment]
This seems to be in full working order. I also tried it out by merging with #10 and things generally worked nicely.

**Comment by jhamman** [comment]
@mrocklin - can you resolve the conflicts here?

**Comment by mrocklin** [comment]
Done

**Pull request merged**
