### PR TITLE
Prettify command template #431

### LINKED ISSUE #431: Make submission script more human readable
```py
from dask_jobqueue import SLURMCluster 
cluster = SLURMCluster(cores=1, memory='1GB') 
print(cluster.job_script()) 
```

```
#!/usr/bin/env bash

#SBATCH -J dask-worker
#SBATCH -n 1
#SBATCH --cpus-per-task=1
#SBATCH --mem=954M
#SBATCH -t 00:30:00

/home/lesteve/miniconda3/bin/python -m distributed.cli.dask_worker tcp://192.168.0.11:44065 --nthreads 1 --memory-limit 1000.00MB --name name --nanny --death-timeout 60
```

Wouldn't it be nice if the last line use backslashes to be more human-readable i.e. something like:
```
/home/lesteve/miniconda3/bin/python -m distributed.cli.dask_worker \
    tcp://192.168.0.11:44065 \
    --nthreads 1 \
    --memory-limit 1000.00MB \
    --name name \
    --nanny --death-timeout 60
```

Full disclosure: not sure if there is an easy way to do this or if you have to write a little bit of code.

### PR DESCRIPTION
**Pull request by AdamWlodarczyk**
More human readable submission script (fix #431).

### CODE REVIEW

**Comment by lesteve** [comment]
`htcondor` failure is unexpected since we haven't seen it before so maybe your PR affects htcondor in an unexpected way ...

Looking quickly at the error log the error does seem genuine (https://github.com/dask/dask-jobqueue/pull/486/checks?check_run_id=1806035437):
```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fd89eaa8f98>>, <Task finished coro=<SpecCluster._correct_state_internal() done, defined at /usr/local/lib/python3.6/site-packages/distributed/deploy/spec.py:325> exception=RuntimeError("Command exited with non-zero exit code.\nExit code: 1\nCommand:\ncondor_submit /tmp/tmp7julzh9w.sh\nstdout:\n\nstderr:\n\nERROR: Can't find address of local schedd\n\n",)>)
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/usr/local/lib64/python3.6/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.6/site-packages/distributed/deploy/spec.py", line 360, in _correct_state_internal
    await w  # for tornado gen.coroutine support
  File "/usr/local/lib/python3.6/site-packages/distributed/deploy/spec.py", line 71, in _
    await self.start()
  File "/dask-jobqueue/dask_jobqueue/core.py", line 337, in start
    out = await self._submit_job(fn)
  File "/dask-jobqueue/dask_jobqueue/core.py", line 320, in _submit_job
    return self._call(shlex.split(self.submit_command) + [script_filename])
  File "/dask-jobqueue/dask_jobqueue/core.py", line 420, in _call
    "stderr:\n{}\n".format(proc.returncode, cmd_str, out, err)
RuntimeError: Command exited with non-zero exit code.
Exit code: 1
Command:
condor_submit /tmp/tmp7julzh9w.sh
stdout:

stderr:

ERROR: Can't find address of local schedd
```

I am not super convinced there needs to be a `pretty` argument in principle you can use the command with `\` in the script. `htcondor` may be weird in this respect IIRC but I am not a `htcondor` expert (basically the file you are submitting is not a shell script it is some kind of `htcondor` configuration file).

For completeness, I edited your PR description to use "Fix #issueNumber", this way the associated issue gets closed automatically when the PR is merged. For more details, look at [this](https://github.com/blog/1506-closing-issues-via-pull-requests).

**Comment by mivade** [comment]
I haven't had time yet to fully dig into this but `Can't find address of local schedd` indicates an error submitting the job (`schedd` is kinda sorta the scheduler daemon).

**Comment by mivade** [comment]
OK I think the issue has to do with the backslashes. Here's an example of what the submit script looks like when `pretty=True`:

```
#!/usr/bin/env condor_submit

MY.DaskWorkerName = "htcondor--$F(MY.JobId)--"
RequestCpus = MY.DaskWorkerCores
RequestMemory = floor(MY.DaskWorkerMemory / 1048576)
RequestDisk = floor(MY.DaskWorkerDisk / 1024)
MY.JobId = "$(ClusterId).$(ProcId)"
MY.DaskWorkerCores = 1
MY.DaskWorkerMemory = 1000000000
MY.DaskWorkerDisk = 1000000000

Environment = ""
Arguments = "-c '/Users/michael.depalatis/tmp/dask-jobqueue/env/bin/python -m distributed.cli.dask_worker \
    tcp://192.168.0.110:50573 \
    --nthreads 1 \
    --memory-limit 1000.00MB \
    --name dummy-name \
    --nanny \
    --death-timeout 60 \
    --protocol tcp://'"
Executable = /bin/sh

Queue
```

Multi-line variables are treated... interestingly. See [this](https://htcondor.readthedocs.io/en/latest/admin-manual/introduction-to-configuration.html) for details.

**Comment by AdamWlodarczyk** [comment]
@lesteve @mivade Thanks guys for your support. I will try to fix that (hopefully this week).

**Comment by AdamWlodarczyk** [comment]
So I retriggered actions since I couldn't catch that error in local CI checks and htcondor  passes tests. I could get that previous error last week but now it works. Maybe some software update?

**Comment by guillaumeeb** [comment]
Any objection for merging this one from @dask/dask-jobqueue-htcondor ?

**Comment by lesteve** [comment]
Personally I still have this reservation:

> I am not super convinced there needs to be a pretty argument in principle you can use the command with \ in the script. 

Maybe I am missing something but I find it weird that essentially this PR:
- makes the output of `cluster.job_script()` more beautiful (command is multi-line with backslashes)
- but that `cluster.job_script()` is not the actual script that gets submittted (command is single line without back-slashes)

To be honest right now, my feeling is that this is not super clear that the benefits (slightly nicer `cluster.job_script()` output) clearly outweights the costs (makes the code just a bit more complicated and suprising).

**Comment by riedel** [comment]
I understand the intention and really welcome efforts to make debugging easier.

My 2 cents: I really do not get this PR: it seems like a debugging tool (only use inside of debug of logger.debug("Job script: \n %s" % self.job_script())) . Couldn't that be efficiently implemented inside some auxilliary logger addon ? Outside a potentially critical path (what if someone actually uses this outside of print statements?

Particularly changing the default behaviour and then testing the other is a no go for me! So confusing.

Also the PR introduces a lot of unrelated changes. 

Sorry for being so harsh!

**Comment by guillaumeeb** [comment]
Thanks @lesteve and @riedel for your comments. I haven't checked the changes, and did not see @lesteve previous reservation. 

So currently, this PR introduces too many changes and complicated code for too few benefits. So what should be done for fixing #431:
* Change the job script generation (both example and the one that gets submitted).
* Just change the default method, not introducing a new option.
* Test the new behavior.

**Comment by guillaumeeb** [comment]
@AdamWlodarczyk do you intend to work on this again, or should we close this PR for a future fresh start?

**Pull request closed without merging**
