### PR TITLE
Add links to @willirath tutorial

### PR DESCRIPTION
**Pull request by lesteve**
I added them on the docs and in the README. Any comments, let me know!

This is how it looks on the documentation generated locally:

image.

### CODE REVIEW

**Comment by lesteve** [comment]
I wanted to say it is slightly weird to have the Tutorial non-section before the "Getting started" but I figure it is better to make the tutorial prominent rather than hidden in a sub-page.

**Comment by willirath** [comment]
Thanks for adding these!

There's a DOI now: https://doi.org/10.5281/zenodo.3337784

But the look and feel is much nicer in the Github repo.  So I'm not sure which to better include.  The DOI is much more stable, though.

**Comment by willirath** [comment]
> I wanted to say it is slightly weird to have the Tutorial non-section before the "Getting started" but I figure it is better to make the tutorial prominent rather than hidden in a sub-page.

What about putting it in a Tutorials page under "Detailed Use"? There, we could also link the video from the front page and the slides / video of @andersy005's SciPy2019 talk.

**Comment by lesteve** [comment]
I haven't had time to catch up with SciPy I have to admit (just watching Matt's talk now). My not super strong opinions:
* I'd be in favour to make the tutorial(s) prominent. So maybe a reasonable compromise is to have a link with tutorials on the main documentation page that goes to a "Tutorials" sub-section.
* I'd go for the github repo rather than the DOI. user-friendly trumps stability in this particular case.

**Comment by willirath** [comment]
Sounds great!

**Comment by lesteve** [comment]
Pushed an update. I put this in the "Getting started" section, because I feel this is where I would expect a tutorial to show up rather than "detailed use". Let me know what you think.

image

**Comment by willirath** [comment]
Looks great!

**Comment by willirath** [comment]
If there's no objections within the next hour or so, I'd merge.

**Pull request merged**
