### PR TITLE
forward 'ip' to LocalCluster

### PR DESCRIPTION
**Pull request by twoertwein**
JobQueueCluster forwards any additional keyword arguments to LocalCluster. However, it fails to forward 'ip' to the LocalCluster as it is explicitly set. This commit allows the user to forward 'ip' to the LocalCluster.

Context:
My cluster head has two network interfaces (one facing only the workers and one facing the internet). I want the scheduler to only listen on the worker facing interface. The 'interface' argument would be well suited for this task but JobQueueCluster also forwards this interface to the workers. Unfortunately, not all my cluster nodes have the same interface names. Therefore, I have to use 'ip' to force the scheduler to listen on the worker facing interface (without forcing the workers itself to use a (potentially non-existing) interface).
Personally, I would prefer to not force the interface of the workers (in that case I could use 'interface' to set the interface of only the scheduler) but I assume you have a reason for doing so :)

### CODE REVIEW

**Comment by lesteve** [comment]
I am not an expert in this kind of thing but this seems like a problem related to https://github.com/dask/dask-drmaa/issues/75. It would be great if you could add a test similar to the one in https://github.com/dask/dask-drmaa/pull/77.

> Unfortunately, not all my cluster nodes have the same interface names.

Interesting, can I ask whether there is a good reason for this?

> Personally, I would prefer to not force the interface of the workers (in that case I could use 'interface' to set the interface of only the scheduler) but I assume you have a reason for doing so :)

Not sure ... maybe @mrocklin has some inputs on this.

**Comment by twoertwein** [comment]
> I am not an expert in this kind of thing but this seems like a problem related to dask/dask-drmaa#75. It would be great if you could add a test similar to the one in dask/dask-drmaa#77.

Yes, that looks similar. I will look trough how you are doing unit tests and then add one to verify the IP address.

> Interesting, can I ask whether there is a good reason for this?

There is no (good) reason for that. I wish the interfaces across all nodes had the same name. It is a cluster from a university research lab.

> Those changes seem fine to me, thanks. I was searching a way to do that with less 'if' but I'm still not pythonic enough to find one.

This solution would have less if's and it doesn't change the input arguments:

```py
# Find the IP address and (if requested) set interface for workers
locahost_kwargs = {}
if interface:
    locahost_kwargs['ip'] = get_ip_interface(interface)
    extra += ' --interface  %s ' % interface
else:
    locahost_kwargs['ip'] = socket.gethostname()

locahost_kwargs.update(kwargs)
self.local_cluster = LocalCluster(n_workers=0, **locahost_kwargs)
```

**Comment by twoertwein** [comment]
@lesteve about the test case, there are some differences compared to dask/dask-drmaa#77
1) JobQueueCluster should not directly be instantiated. I could add a SLURM test case, but that seems to be the wrong place for it;
2) The requested IP address in dask/dask-drmaa#77 is the same one as JobQueueCluster would use by default, i.e., it wouldn't test anything. I could request an IP address which 'probably' does not coincide with the default IP address by requesting the (probably not-existing) IP address `127.0.0.2` (surprisingly, it does work to insatiate a SLURMCluster with this IP address, even though that machine doesn't have an interface with that ip).

I don't think that using a SLURMCluster (wrong component) with a probably not-existing IP address is a good way to test this PR. Do you have any suggestions?

I will change the PR to reflect @guillaumeeb suggestion - it looks much nicer :)

**Comment by guillaumeeb** [comment]
I'm adding basic tests here, to merge if everything is OK so that we can move on to solve #90.

**Comment by guillaumeeb** [comment]
Getting this in quiclky to propose another PR that solves #90 and allows #111.

Thanks @twoertwein.

**Pull request merged**
