### PR TITLE
Remove use of Sphinx `add_stylesheet()`

### LINKED ISSUE #512: Doc build is failing
Started failing two weeks ago: https://readthedocs.org/projects/dask-jobqueue/builds/14170262/

Very likely a Sphinx change ...

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-jobqueue/conda/latest/lib/python3.6/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-jobqueue/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 257, in __init__
    self.config.setup(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-jobqueue/checkouts/latest/docs/source/conf.py", line 210, in setup
    app.add_stylesheet("basic.css")
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask-jobqueue/checkouts/latest/docs/source/conf.py", line 210, in setup
    app.add_stylesheet("basic.css")
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
```

### PR DESCRIPTION
**Pull request by ocaisa**
Fixes #512

### CODE REVIEW

**Comment by ocaisa** [comment]
Open/closing to retrigger tests

**Comment by ocaisa** [comment]
@lesteve I don't know if this is even still necessary, maybe you know better?

**Comment by lesteve** [comment]
Thanks for the PR!

This was about something in the doc that was weird with sphinx_rtd_theme, I don't really know whether that's still necessary. See https://github.com/dask/dask-jobqueue/pull/301.

Maybe you can build the docs locally to see whether the problem has disappeared with the change in this PR?

We don't build the doc in the PR, we should probably do it with ReadTheDocs ...

**Comment by ocaisa** [comment]
It looks like this is no longer an issue, I built the docs with `sphinx-4.1.1` having commented out the entire block (that version does throw the same error this PR was fixing). The build looks like
Screenshot 2021-07-22 15 00 15
so I think the issue in #301 is resolved. I'll update to remove that whole section.

**Comment by lesteve** [comment]
OK after following the doc and trying many different things it looks like ReadTheDocs is enabled in PRs now (it was enabled but something was misconfigured somehow maybe at the webhook level not sure) ...

**Comment by lesteve** [comment]
@ocaisa I completely trust you but just in case I'll double-check the build on ReadTheDocs: https://readthedocs.org/projects/dask-jobqueue/builds/14300647/ ...

**Comment by lesteve** [comment]
OK it looks good, thanks a lot @ocaisa, merging!

**Comment by lesteve** [comment]
By the way, just curious, do you see too long lines too in your local build:
image

**Comment by ocaisa** [comment]
@lesteve Yes I see the same thing locally, lines are too long

**Pull request merged**
