### PR TITLE
Prepare for Dask 2.3.0 release

### PR DESCRIPTION
**Pull request by jrbourbeau**
This is just to test against the current `master` branch of `dask/dask` and `dask/distributed` prior to releasing `2.3.0` upstream

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for handling this @jrbourbeau .  I *hope* that this work all gets replaced in the near-to-moderate future with the SpecCluster rewrite (#307) , but until then it's quite nice to maintain continuity.

**Comment by jrbourbeau** [comment]
Thanks for pointing me to #307, looking forward to seeing it included

> until then it's quite nice to maintain continuity

Just to be clear, you mean continuity with `distributed` right? Fortunately, it looks like adding a `scheduler_info` attribute was the only addition needed for compatibility with the current `distributed` `master`

**Comment by mrocklin** [comment]
Yes, I mean that it'll be nice to make sure that things continue to work
for users while we continue to work on the SpecCluster rewrite.  I hope
that *after* that rewrite, the dask-jobqueue package becomes much smaller
and requires less maintenance.

**Comment by jrbourbeau** [comment]
> the dask-jobqueue package becomes much smaller
and requires less maintenance

+1 😄 

Things look good here (the CI is passing against upstream `master`s), so I'll go ahead and revert back to testing against the latest release

**Comment by mrocklin** [comment]
Thanks @jrbourbeau !

**Comment by mrocklin** [comment]
@guillaumeeb is it ok if I push out a release for dask 2.3 compatibility?

**Comment by guillaumeeb** [comment]
Sure! No problem from me. We have to ensure that jobqueue is compatible with the latest Dask version!

**Comment by mrocklin** [comment]
Done

**Comment by lesteve** [comment]
Thanks for this! FYI I pushed a minor change in the changelog to make it more clear that dask-jobqueue 0.6.3 is compatible with dask 2.3.0

**Pull request merged**
