### PR TITLE
Add doe arm

### PR DESCRIPTION
**Pull request by josephhardinee**
Added the Department of Energy - Atmosheric Radiation Measurement stratus cluster to configuration examples.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks @josephhardinee .  This looks great.  Should we wait to learn if this applies to all of Titan or should we merge sooner?

**Comment by josephhardinee** [comment]
I think merging for now is fine and we'll just call it instructions for ARM's stratus cluster as it's open to quite a few users of dask as well.

**Comment by mrocklin** [comment]
OK, if you do find that this applies to Titan as well then an update would be well appreciated.  Presumably there are users of Titan that won't recognize this name.

Merging.

**Comment by bstrdsmkr** [comment]
No no, these look fine, mostly just wanted to leave a record in case it suddenly stopped working for someone (we're shooting for a timescale in days).

What's the best way to get in touch aside from highjacking @josephhardinee 's PR thread? :)

**Comment by mrocklin** [comment]
We tend to do most of our communication direclty on Github.  I recommend
opening a new issue at https://github.com/dask/dask-jobqueue/issues/new

**Pull request merged**
