### PR TITLE
Kick-off doc section about common work-arounds.

### PR DESCRIPTION
**Pull request by lesteve**
This is about https://github.com/dask/dask-jobqueue/issues/356 and also because recently #196 led me to realise there was no nice place where to fit his proposed work-around for job arrays

### CODE REVIEW

**Comment by lesteve** [comment]
I am going to merge this one to kick off this common work-arounds page.

@guillaumeeb or @willirath if you happen to have five minutes to look at this page and have some suggestions, this would be more than welcome!

**Comment by guillaumeeb** [comment]
Thanks @lesteve.

I was also wondering were to put the documentation for #122. But I'm not sure this is a "work-around", this sounds more like a "how to that" chapter. Do you think we should add another section, or just rename this new one to something more general?

**Comment by lesteve** [comment]
#122 feels like a work-around to me but I agree work-around is not a great name.

This could be made more general like cookbook or advanced tips and tricks or a better name if you can think of one ...

**Comment by guillaumeeb** [comment]
Yeah, I prefer something like "Advanced tips and tricks" or something like that,

"Advanced pratices" ?
just "Tips and Tricks" ?
"Advanced use cases" ?

**Comment by lesteve** [comment]
Advanced tips and tricks works for me, let me do the renaming.

**Comment by lesteve** [comment]
Renaming done in https://github.com/dask/dask-jobqueue/commit/bb89969d9c6cabcae66c900409872bb29e060e62.

**Pull request merged**
