### PR TITLE
Fix Slurm CI failure

### LINKED ISSUE #67: CI build problem on SLURM test
There seems to be a problem with SLURM CI test, I've seen this in several PRs : https://travis-ci.org/dask/dask-jobqueue/jobs/387815778

A job seems to be fail at submission.

```
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.6.0, py-1.5.3, pluggy-0.6.0 -- /opt/anaconda/bin/python
cachedir: .pytest_cache
rootdir: /dask-jobqueue, inifile:
collected 11 items                                                             
dask_jobqueue/tests/test_jobqueue_core.py::test_jq_core_placeholder PASSED [  9%]
dask_jobqueue/tests/test_jobqueue_core.py::test_errors PASSED            [ 18%]
dask_jobqueue/tests/test_pbs.py::test_header PASSED                      [ 27%]
dask_jobqueue/tests/test_pbs.py::test_job_script PASSED                  [ 36%]
dask_jobqueue/tests/test_pbs.py::test_basic SKIPPED                      [ 45%]
dask_jobqueue/tests/test_pbs.py::test_adaptive SKIPPED                   [ 54%]
dask_jobqueue/tests/test_sge.py::test_basic SKIPPED                      [ 63%]
dask_jobqueue/tests/test_slurm.py::test_header PASSED                    [ 72%]
dask_jobqueue/tests/test_slurm.py::test_job_script PASSED                [ 81%]
dask_jobqueue/tests/test_slurm.py::test_basic FAILED                     [ 90%]
dask_jobqueue/tests/test_slurm.py::test_adaptive PASSED                  [100%]
=================================== FAILURES ===================================
__________________________________ test_basic __________________________________
loop = <tornado.platform.asyncio.AsyncIOLoop object at 0x7f934bd42390>
    @pytest.mark.env("slurm")  # noqa: F811
    def test_basic(loop):
        with SLURMCluster(walltime='00:02:00', threads=2, processes=1, memory='4GB',
                          job_extra=['-D /'], loop=loop) as cluster:
            with Client(cluster) as client:
                workers = cluster.start_workers(2)
                future = client.submit(lambda x: x + 1, 10)
                assert future.result(60) == 11
                assert cluster.jobs
    
                info = client.scheduler_info()
                w = list(info['workers'].values())[0]
                assert w['memory_limit'] == 4e9
                assert w['ncores'] == 2
    
                cluster.stop_workers(workers)
    
                start = time()
                while len(client.scheduler_info()['workers']) > 0:
                    sleep(0.100)
>                   assert time() < start + 10
E                   assert 1528123387.6426318 < (1528123377.581219 + 10)
E                    +  where 1528123387.6426318 = time()
dask_jobqueue/tests/test_slurm.py:104: AssertionError
------------------------------ Captured log call -------------------------------
core.py                    210 ERROR    sbatch: error: Batch job submission failed: Unable to contact slurm controller (connect failure)
core.py                    210 ERROR    scancel: error: Invalid job id
================ 1 failed, 7 passed, 3 skipped in 36.07 seconds ================
```

### PR DESCRIPTION
**Pull request by guillaumeeb**
First test for triggering travis. Fixed the problem in start-slurm.sh raised by @lesteve 

Closes #67

### CODE REVIEW

**Comment by mrocklin** [comment]
It looks like everything passed!  Nice!

**Comment by lesteve** [comment]
I checked in the Travis log and I see mutiple `Waiting for SLURM cluster to become ready` so it seems like this was the problem inceed. Thanks a lot for the fix, merging!

**Comment by mrocklin** [comment]
Thanks @guillaumeeb !

**Comment by lesteve** [comment]
I am guessing the reason the problem seemed to appear out of nowhere, was because we were just lucky before and the cluster was setup correctly on the first attempt.

**Pull request merged**
