### PR TITLE
Handle dask-worker command args and `extra` kwargs as a list

### LINKED ISSUE #156: Missing space using extra in PBSCluster
Hi guys,

First post on Github for me... newbie.
I found an issue using  keyword "extra" in PBSCluster:

`cluster = PBSCluster(extra="--preload my_module.py") 

'cluster.job_script()'
returns
'#!/bin/bash\n\n#PBS -N dask-worker\n#PBS -q mpi_1\n#PBS -A SKIM\n#PBS -l select=1:ncpus=28:mem=120GB\n#PBS -l walltime=24:00:00\n#PBS -m n\n\n\n\n/home1/datahome/fnouguie/miniconda3/envs/lops-array/bin/python -m distributed.cli.dask_worker tcp://10.148.1.18:56677 --nthreads 2 --nprocs 28 --memory-limit 3.57GB --name dask-worker-2 --death-timeout 900--preload my_module.py --interface  ib0 \n'

showing no white space between 900 and --preload leading to the error.
I manually added a white space as a first character of  my extra command to PBSCluster to bypass the error.
Seems like a small bug.

### PR DESCRIPTION
**Pull request by guillaumeeb**
Fixes #156

### CODE REVIEW

**Comment by willirath** [comment]
Just a comment that is beyond the scope of this PR:  Keeping track of all the CLI args to dask-worker in a `list_of_all_args` (see [the recommended way of passing args to `subprocess`](https://docs.python.org/3/library/subprocess.html#frequently-used-argument)) and eventually do `" ".join(list_of_all_args)` would be a general way of solving this.

**Comment by guillaumeeb** [comment]
@willirath this would probably be cleaner yes, but should we change the `extra` constructor kwargs to be also a list then?

**Comment by willirath** [comment]
> but should we change the `extra` constructor kwargs to be also a list then?

My personal feeling says: Yes, passing CLI args as a sequence is standard any way.  But I'm not sure if that's representative.

**Comment by guillaumeeb** [comment]
Okay, so I chose to follow your suggestion @willirath.

**Comment by guillaumeeb** [comment]
Travis was also having a difficult monday apprently.

**Comment by guillaumeeb** [comment]
@willirath, since you've made the comment about using a list of args, a review would be welcome!

**Comment by guillaumeeb** [comment]
Few, thanks for that @willirath, no real testing from my part before your comments... Glad you saw those mistakes.

**Comment by guillaumeeb** [comment]
Thanks @willirath, feel free to take a look at other PR/issues if you find the time. It could be nice to have another core maintainer.

**Comment by willirath** [comment]
> Thanks @willirath, feel free to take a look at other PR/issues if you find the time. It could be nice to have another core maintainer.

Sounds good.  I'm not sure I'll have much time for continuous work. But it sure looks like dask clusters and dask-jobqueue will play a increasingly role in my and my group's routine work. So count me in!

**Comment by guillaumeeb** [comment]
Nice ! 

We're all on the same situation about time 🙂 !

**Pull request merged**
