### PR TITLE
Use a mix of processes and threads when processes is not specified

### LINKED ISSUE #332: Should we default to multiple processes (rather than multiple threads)?
```py
from dask_jobqueue import SLURMCluster
cluster = SLURMCluster(cores=4, memory='16GB')
[line for line in cluster.job_script().splitlines() if 'dask_worker' in line]
```

Excerpt of the output:
```
python -m distributed.cli.dask_worker --nthreads 4 ...
```

So by default we use one dask worker with 4 threads. This does not seem ideal.
In a Python world (because of the GIL), using multi-processing by default for parallelism is more likely to increase performance.

Maybe we can use the same heuristic of processes vs threads as `LocalCluster` (`distributed.deploy.local.nprocesses_nthreads`):
https://github.com/dask/distributed/blob/ad0c7c23c384e981e0622c36e7fb132429becc34/distributed/deploy/local.py#L211
summary of the heuristic:
* `if cores <= 4, processes=cores, threads_per_process=1`
* `if cores > 4, processes ~= sqrt(cores), threads_per_process ~= sqrt(cores)` and `processes > threads_per_process`

### PR DESCRIPTION
**Pull request by lesteve**
Fixes #332, closes #334.

### CODE REVIEW

**Comment by lesteve** [comment]
@jennirinker I took over your PR #334, any comments let me know!

**Comment by lesteve** [comment]
Good point, I will add some documentation in the docstring for the default value of `processes`.

I have to say I don't remember why/how the mix of processes/threads was chosen for `LocalCluster` but I trust there was a good reason behind it.

My main worry is that the default (when specifying only `cores` and not `processes`) is going to use only multithreading and will make `dask-jobqueue` look bad in most cases (Python functions which don't release the GIL).

**Comment by mrocklin** [comment]
The heuristic was intended to find a good balance between the two.  My experience is that machines with 20+ cores don't get full parallelism with only threads, and that separating these into a few processes tends to help.  It could be though that workloads that run on HPC centers tend to be more GIL friendly (more numpy, less text).  I don't know though.

I've never really regretted having large nodes cut up into a few processes, so In general I'm mildly in favor of this change.  I can understand not wanting it too though for explicitness.

**Comment by lesteve** [comment]
I pushed an entry in changelog. I am going to merge this one.

**Pull request merged**
