### PR TITLE
Support older HTCondor versions without -file argument

### PR DESCRIPTION
**Pull request by lesteve**
Split off from #319.

@matyasselmeci is that what you had in mind?

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Yep, exactly.

**Comment by lesteve** [comment]
OK I am going to merge this then, thanks for your feed-back!

@simone-codeluppi since you had the issue, it would be great if you could confirm that using `dask-jobqueue` master (e.g. through `pip install git+https://github.com/dask/dask-jobqueue`) fixes the issue you saw in #350.

**Comment by simone-codeluppi** [comment]
@lesteve the `dask-jobqueue` master fixed my issue. Thanks for fix it!

**Comment by lesteve** [comment]
Great thanks for the confirmation!

**Pull request merged**
