### PR TITLE
Switch from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Thought I would try a quick lift and shift from Travis to GitHub Actions.

I've reproduced exactly the Travis config in GitHub Actions config, however there's a bunch of scope for replacing some of the CI scripts with Actions from the Marketplace. Conda setup, for example, is [done like this](https://github.com/dask/distributed/blob/master/.github/workflows/ci-windows.yaml#L17-L24) in the distributed Windows CI.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Ended up using the Conda setup action to get things to pass. The script wasn't working for some reason.

Build is now successful. https://github.com/jacobtomlinson/dask-jobqueue/actions/runs/116941234

I think checks only report here once merged.

**Comment by willirath** [comment]
Github limits free use of actions to [2,000 minutes / month / org](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions). Is this something that could become problematic?

**Comment by jacobtomlinson** [comment]
My understanding is that PRs count against the user's limit, not the orgs. So we only need to worry about minutes spent testing master. But that is still something to bear in mind.

I think it is also possible for Dask to fund things like this is it brings enough benefit to the community. And in my opinion better and fast CI, leads to a better contribution experience, leads to more contributions is a benefit to us. To buy another 2,000 minutes is only $16. But perhaps @mrocklin could weigh in here?

**Comment by lesteve** [comment]
> Github limits free use of actions to 2,000 minutes / month / org. Is this something that could become problematic?

From [this](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions):

> GitHub Actions usage is free for public repositories. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account.

so if I understand things correctly the 2000 minutes / month / org is only for private repositories, right?

**Comment by willirath** [comment]
> GitHub Actions usage is free for public repositories.

Jumped right to the table.  Thanks for point this out!

**Comment by lesteve** [comment]
OK I am going to merge this one, I have no informed opinion on whether Travis or Github Actions is significantly better so I am going to fully trust @jacobtomlinson on this one. Thanks a lot for the PR!

**Comment by lesteve** [comment]
It looks like the Github Actions CI is running on master as Jacob said: https://github.com/dask/dask-jobqueue/actions/runs/122951522

**Pull request merged**
